travis:
  secure:
    BINSTAR_TOKEN: UG8gItb3VWSJ8OTOs1/CBIFE0O2gFtgFBvgyB/vET1OZeB2tqeY3ekZJytdoi7Hy6cR9ilTj4i5oxE2CaDZS+t6DFEpJa5uFfYOoAlCXtKQ4UODp8xprq6YkT73+W5EbnhjN/4aqJ48UvecyooywpJDDLm5b8hzrbYq+wwsFhpSAdpVGmeecG4QT6FBALI2PX2Yn76XKJWelg54iQWoHByD+bVOCjUHIQkwZCy0y0jvomLkJo8nysYnkCzmZsyVhDT5Wvt73gZKoyD27ijw3A/rDxYwMgOaI8Z94JozpBKfTozTLh9mp6ItGggRmkMU2fZ5WTrZhhE5h3syQLHTL8lVkKG6Zc1f8c5uiqtz63a/FPI27tDJ+DNy9jrQQyCHA8Rf3OaSDoO9UFabGtxB+LRU/BoFfjsJEnHsfn0b2OKf4vgWUypoCE7Z/w+qgchmQbwrGv75PFDOMCBpgX6d1iRY+PTm96J/RGOX9ce4c4qxT1iYOHEC4PGYnDvCtXCgtDOXS0Hvoqo6Lco5/ULwvnlOzPeSgxBRrMVZWRbZWYqLWYmxnson4zPKUSMB1bV9hwbC51vFFRFZ+BGA/6rQm3LKXeYULiUHSvmzmjwFQ7YKn1kVLL44H/w3OhS1XBOEDxc0sfoErY+HKtwR3vnQJC6uQ+9a99MA7Wwqb4zOczQY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
